version: "3"
services:
  formsg-redis:
    image: redis
    ports:
      - "6379:6379"
  formsg-mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/data/db:/data/db
  formsg-dev:
    build:
      context: ./
      dockerfile: Dockerfile
    image: formsg-dev
    ports:
      - "5000:5000"
    links:
      - formsg-redis:redis-db
      - formsg-mongo:db
    env_file:
      - .env
